# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='LabDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQ', 'Requested'), ('APP', 'Approved'), ('REF', 'Refused'), ('ORD', 'Ordered'), ('REC', 'Received'), ('REG', 'Registered'), ('AVA', 'Available (Public)'), ('ASS', 'Assigned (Dedicated)'), ('WIT', 'Withdrawn'), ('BRO', 'Broken'), ('REP', 'In repair'), ('RET', 'Retired (Recycled)')], max_length=3)),
                ('device_sn', models.CharField(max_length=100)),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='date device registered')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestedDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQ', 'Requested'), ('APP', 'Approved'), ('REF', 'Refused'), ('ORD', 'Ordered'), ('REC', 'Received'), ('REG', 'Registered'), ('AVA', 'Available (Public)'), ('ASS', 'Assigned (Dedicated)'), ('WIT', 'Withdrawn'), ('BRO', 'Broken'), ('REP', 'In repair'), ('RET', 'Retired (Recycled)')], max_length=3)),
                ('model_type', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('os_version', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='date request submitted')),
                ('approve_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date request approved')),
                ('po_date', models.DateTimeField(blank=True, null=True, verbose_name='date purchase started')),
                ('po_number', models.CharField(blank=True, max_length=15)),
                ('price_usd', models.CharField(blank=True, max_length=15)),
                ('price_cny', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap', models.CharField(max_length=30)),
                ('cost_center', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=50)),
                ('device_owner', models.CharField(max_length=100)),
                ('device_label', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='requesteddevice',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motric.Requester'),
        ),
        migrations.AddField(
            model_name='labdevice',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='motric.RequestedDevice'),
        ),
        migrations.AddField(
            model_name='event',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motric.LabDevice'),
        ),
    ]
