# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddevice',
            name='ex_rate',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesteddevice',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labdevice',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date device_sn recorded'),
        ),
        migrations.AlterField(
            model_name='requesteddevice',
            name='approve_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='requesteddevice',
            name='po_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesteddevice',
            name='price_cny',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='requesteddevice',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='requesteddevice',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
