# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labdevice',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motric.RequestedDevice'),
        ),
    ]
