# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0002_auto_20160704_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteddevice',
            name='ex_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='requesteddevice',
            name='price_cny',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='requesteddevice',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
