# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0003_auto_20160817_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='labdevice',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
