# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0004_auto_20160704_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteddevice',
            name='price_usd',
            field=models.FloatField(blank=True),
        ),
    ]
