# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0004_labdevice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labdevice',
            old_name='device_sn',
            new_name='device_id',
        ),
        migrations.AddField(
            model_name='labdevice',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='labdevice',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='labdevice',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='labdevice',
            name='project',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='requester',
            name='device_label',
            field=models.CharField(max_length=50),
        ),
    ]
