# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0005_auto_20160704_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteddevice',
            name='price_cny',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2),
        ),
    ]
