# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0005_auto_20160824_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labdevice',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labdevice',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date device_id recorded'),
        ),
    ]
