# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0006_auto_20160826_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdevice',
            name='model',
        ),
        migrations.AddField(
            model_name='labdevice',
            name='model',
            field=models.ManyToManyField(to='motric.RequestedDevice'),
        ),
    ]
