# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0008_auto_20160906_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='labdevice',
            name='replaced_by',
            field=models.ManyToManyField(related_name='_labdevice_replaced_by_+', to='motric.LabDevice'),
        ),
    ]
