# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0010_auto_20160704_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteddevice',
            name='price_cny',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='requesteddevice',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6),
        ),
    ]
