# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0011_requester_pref_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='pref_location',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
