# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0013_auto_20160921_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdevice',
            name='respond_to',
        ),
    ]
