# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0014_remove_labdevice_respond_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motric.LabDevice')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motric.RequestedDevice')),
            ],
        ),
        migrations.AddField(
            model_name='labdevice',
            name='respond_to',
            field=models.ManyToManyField(through='motric.ResponseRelationship', to='motric.RequestedDevice'),
        ),
    ]
