# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0016_auto_20160930_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddevice',
            name='receive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
