# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0017_requesteddevice_receive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddevice',
            name='comment',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
