# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0020_auto_20170112_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteddevice',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='requesteddevice',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
