# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0021_auto_20170118_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labdevice',
            name='status',
            field=models.CharField(choices=[('REQ', 'Requested'), ('APP', 'Approved'), ('REF', 'Refused'), ('ORD', 'Ordered'), ('REC', 'Received'), ('REG', 'Registered'), ('AVA', 'Public'), ('ASS', 'Assigned'), ('WIT', 'Withdrawn'), ('BRO', 'Broken'), ('REP', 'In Repair'), ('RET', 'Retrieved'), ('RTR', 'Retired (Recycled)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='requesteddevice',
            name='status',
            field=models.CharField(choices=[('REQ', 'Requested'), ('APP', 'Approved'), ('REF', 'Refused'), ('ORD', 'Ordered'), ('REC', 'Received'), ('REG', 'Registered'), ('AVA', 'Public'), ('ASS', 'Assigned'), ('WIT', 'Withdrawn'), ('BRO', 'Broken'), ('REP', 'In Repair'), ('RET', 'Retrieved'), ('RTR', 'Retired (Recycled)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='requester',
            name='device_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requester',
            name='pref_location',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
