# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0022_auto_20170222_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddevice',
            name='charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labdevice',
            name='status',
            field=models.CharField(choices=[('REQ', 'Requested'), ('APP', 'Approved'), ('REF', 'Refused'), ('ORD', 'Ordered'), ('REC', 'Received'), ('REG', 'Registered'), ('AVA', 'Public'), ('ASS', 'Assigned'), ('WIT', 'Withdrawn'), ('BRO', 'Broken'), ('REP', 'In Repair'), ('RET', 'Retrieved'), ('RTR', 'Retired')], max_length=3),
        ),
        migrations.AlterField(
            model_name='requesteddevice',
            name='status',
            field=models.CharField(choices=[('REQ', 'Requested'), ('APP', 'Approved'), ('REF', 'Refused'), ('ORD', 'Ordered'), ('REC', 'Received'), ('REG', 'Registered'), ('AVA', 'Public'), ('ASS', 'Assigned'), ('WIT', 'Withdrawn'), ('BRO', 'Broken'), ('REP', 'In Repair'), ('RET', 'Retrieved'), ('RTR', 'Retired')], max_length=3),
        ),
    ]
