# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0023_auto_20170223_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddevice',
            name='bug_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
