# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0025_auto_20170310_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='labdevice',
            name='po_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
