# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0026_labdevice_po_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='labdevice',
            name='replaced',
            field=models.BooleanField(default=False),
        ),
    ]
