# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0027_labdevice_replaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labdevice',
            name='replaced_by',
            field=models.ManyToManyField(blank=True, null=True, to='motric.LabDevice'),
        ),
    ]
