# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0029_auto_20170413_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labdevice',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labdevice',
            name='owner',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
        migrations.AlterField(
            model_name='labdevice',
            name='project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labdevice',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
