# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0031_auto_20170414_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labdevice',
            name='device_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labdevice',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
