# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0032_auto_20170418_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labdevice',
            name='device_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
