# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0033_auto_20170418_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('101', 'cannot power on'), ('102', 'screen cannot go light'), ('103', 'screen touch broken'), ('104', 'scramble screen'), ('105', 'wifi hardware broken'), ('106', 'sdcard broken'), ('107', 'battery broken'), ('108', 'screen fragmentation'), ('201', 'disconnected via usb'), ('202', 'offline via usb'), ('203', 'unauthorized via usb'), ('204', 'lose internet connection'), ('205', 'stuck on fastboot screen'), ('206', 'stuck on splash screen'), ('207', 'stuck on white screen'), ('208', 'reboot loop')], max_length=4)),
                ('occur_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='labdevice',
            name='broken_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labdevice',
            name='replaced_by',
            field=models.ManyToManyField(blank=True, to='motric.LabDevice'),
        ),
        migrations.AddField(
            model_name='malfunction',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motric.LabDevice'),
        ),
    ]
