# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0036_auto_20170620_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_for', models.CharField(choices=[('FT', 'Functionality Test'), ('SHT', 'System Health(battery, memory, latency) Test'), ('ST', 'Stablity Test'), ('NTU', 'Non-testing Usage'), ('OTR', 'Others')], max_length=3)),
                ('others_detail', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='requesteddevice',
            name='used_for',
        ),
        migrations.AddField(
            model_name='usage',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motric.RequestedDevice'),
        ),
    ]
