# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0037_auto_20170620_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddevice',
            name='eta_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
