# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0038_requesteddevice_eta_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddevice',
            name='assignee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
