# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0039_requesteddevice_assignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='requester',
            name='ldap',
            field=models.CharField(max_length=100),
        ),
    ]
