# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0040_auto_20170803_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='q_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='searcher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
