# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0042_auto_20170804_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='labdevice',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
