# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-26 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0043_labdevice_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='bug_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requesteddevice',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
