# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-21 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0044_auto_20180626_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQ', 'Requested'), ('APP', 'Approved'), ('REF', 'Refused'), ('ORD', 'Ordered'), ('REC', 'Received'), ('REG', 'Registered'), ('AVA', 'Public'), ('ASS', 'Assigned'), ('WIT', 'Withdrawn'), ('BRO', 'Broken'), ('REP', 'In Repair'), ('RET', 'Retrieved'), ('RTR', 'Retired')], max_length=3)),
                ('ldap', models.CharField(max_length=100)),
                ('mdb', models.CharField(max_length=100)),
                ('pe', models.CharField(max_length=300)),
                ('pe_poc', models.CharField(max_length=100)),
                ('model_type', models.CharField(max_length=30)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('comment', models.CharField(blank=True, max_length=1024, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
