# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-19 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motric', '0046_auto_20200612_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotadevice',
            name='floating',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='quotadevice',
            name='usecase',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
